spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root
      url: jdbc:mysql://47.107.172.13:3306/w_smart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: cn.lzy.waterindex.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


server:
  servlet:
    context-path: /smart-service
  port: 5555

file:
  path: e://test1/

logging:
  level:
    root: info
    com.wang.analyze.mapper: debug
    com:
      alibaba:
        nacos:
          client:
            naming: error

#  file: logs/waterindex.log